from binary_search_tree import *

bst = BinarySearchTree(True)
bst.buildBinarySearchTree()
print("Inorder Traversal of Binary Search Tree:")
bst.inorderTraversal()
print('Inserting 210 at index 2')
bst.insert_at(2,210)
bst.inorderTraversal()
print('First common ancestor 210 and 30')
print(bst.firstCommonAncestor(210, 30))
print('Deleting 20')
bst.delete(20)
bst.inorderTraversal()
print('Deleting 10')
bst.delete(10)
bst.inorderTraversal()
print('Inserting 10 at index 4')
bst.insert_at(4,10)
bst.inorderTraversal()
print('First Common 15,30')
bst.firstCommonAncestor(15,30)
bst.printTree()
